name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: g++ main.cpp

      - name: Run
        run: .\a.exe

  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: g++ main.cpp

      - name: Run
        run: ./a.out

  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: g++ main.cpp

      - name: Run
        run: ./a.out