name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Visual Studio Installer Project
        run: |
          .\webrequest.ps1
          $ENV:Path="C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service;"+$ENV:Path
          $result = Start-Process "VSIXInstaller" -ArgumentList "VSInstallerProjSetup.vsix /quiet" -PassThru -Wait
          Write-Host "VSIXInstaller ExitCode:"$result.ExitCode
          rm .\VSInstallerProjSetup.vsix
          if($result.ExitCode -eq 0) { throw "VSIX installed." }
          
      - name: End
        run: echo "End workflow"