name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Visual Studio Installer Project
        run: |
          .\webrequest.ps1
          $ENV:Path="C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE;"+$ENV:Path
          $result = Start-Process "VSIXInstaller" -ArgumentList "VSInstallerProjSetup.vsix /quiet" -PassThru -Wait
          Write-Output $result.ExitCode
          rm .\VSInstallerProjSetup.vsix
          
      - name: End
        run: echo "End workflow"