name: devenv

on:
  push:
    branches:
    - release
  pull_request:
    branches:
    - release

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: run devenv
        run: |
          Start-Process -FilePath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe" -ArgumentList "Windows\DermAnnotation.sln /project Windows\DermAnnotationSetup\DermAnnotationSetup.vdproj /build Release"