name: pr

on:
  pull_request:
    branches:
    - main

jobs:
  windows:
    runs-on: windows-2022
    if: ${{ github.head_ref }} == 'test'
    steps:
      - uses: actions/checkout@v2
        
      - name: Echo
        run: ${{ github.head_ref }}