name: test

on:
  push:
    tags:
      - "*"

jobs:
  github_actions_test:
    name: Test GitHub Actions
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .\file1.txt
            .\file2.txt
